volumes:
  cargo_target:


services:
  frontend:    
    command: /bin/sh -c "while sleep 1000; do :; done"
    
    volumes:
      - ../backend/:/usr/src/app/backend
      - cargo_target:/usr/src/app/backend/target
