volumes:
  node_modules:

services:
  backend:
    command: /bin/sh -c "while sleep 1000; do :; done"

  frontend:
    volumes:
      - ../frontend/:/usr/src/app/frontend
      - node_modules:/usr/src/app/frontend/node_modules
