services:
  api:
    container_name: zapping-app-backend-dev
    build:
      dockerfile: Dockerfile.dev

    volumes:
      - ../../:/usr/src/app
      
    depends_on:
      db:
        condition: service_healthy

    ports:
      - 3000:3000
    environment:
      - PGHOST=db
      - PGUSER=user
      - PGPASSWORD=password
      - PGPORT=5432
      - PGDATABASE=zapping
  
  db:
    container_name: database-dev
    image: postgres:16.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zapping
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
