FROM mcr.microsoft.com/devcontainers/rust:1-1

RUN apt-get update && apt-get install -yy pipx && pipx install gdown
WORKDIR /usr/video
RUN pipx run gdown 1exGq6BJ6r1lXezOanp88sWwxqcMbDntJ -O file.zip \
    && unzip file.zip -d . \
    && mv "hls test" videos \
    && rm file.zip
ENV VIDEOS_PATH=/usr/video/videos


